project_id = "wcpifcdwomjzmvnvgqwr"

[functions.notify-telegram]
verify_jwt = false

[functions.dolly-telegram]
verify_jwt = false

[functions.telegram-setup]
verify_jwt = true

[functions.paypal-config]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false
