create table if not exists public.product_likes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  visitor_token text not null,
  liked_at timestamptz not null default now(),
  unique (product_id, visitor_token)
);

alter table public.product_likes enable row level security;
create index if not exists product_likes_product_id_idx on public.product_likes (product_id);

create or replace function public.toggle_product_like(p_product_id bigint, p_visitor_token text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare liked boolean; total integer;
begin
  if p_visitor_token is null or length(p_visitor_token) < 16 or length(p_visitor_token) > 100 then
    raise exception 'Ungültige Sitzung.' using errcode = '22023';
  end if;
  if not exists (select 1 from public.products where id = p_product_id and active = true) then
    raise exception 'Produkt nicht gefunden.' using errcode = '22023';
  end if;
  if exists (select 1 from public.product_likes where product_id = p_product_id and visitor_token = p_visitor_token) then
    delete from public.product_likes where product_id = p_product_id and visitor_token = p_visitor_token;
    liked := false;
  else
    insert into public.product_likes (product_id, visitor_token) values (p_product_id, p_visitor_token) on conflict do nothing;
    liked := true;
  end if;
  select count(*)::integer into total from public.product_likes where product_id = p_product_id;
  return json_build_object('liked', liked, 'count', total);
end;
$$;

create or replace function public.get_product_like_counts()
returns json
language sql
security definer
set search_path = public
as $$
  select coalesce(json_agg(json_build_object('product_id', like_counts.product_id, 'likes', like_counts.likes)), '[]'::json)
  from (
    select p.id as product_id, count(pl.id)::integer as likes
    from public.products p left join public.product_likes pl on pl.product_id = p.id
    where p.active = true
    group by p.id
  ) like_counts;
$$;

grant execute on function public.toggle_product_like(bigint, text) to anon, authenticated;
grant execute on function public.get_product_like_counts() to anon, authenticated;
