create table if not exists public.paypal_transactions (
  id bigint generated by default as identity primary key,
  own_product_id bigint not null references public.own_products(id) on delete restrict,
  paypal_order_id text not null unique,
  status text not null default 'CREATED',
  amount numeric(10,2) not null,
  currency text not null default 'EUR',
  payer_email text,
  created_at timestamptz not null default now(),
  captured_at timestamptz,
  constraint paypal_transaction_status check (status in ('CREATED','COMPLETED','CANCELLED','FAILED'))
);

alter table public.paypal_transactions enable row level security;
drop policy if exists "Admins can read PayPal transactions" on public.paypal_transactions;
create policy "Admins can read PayPal transactions"
  on public.paypal_transactions for select to authenticated
  using ((select public.is_admin()));

grant select on public.paypal_transactions to authenticated;
grant usage, select on sequence public.paypal_transactions_id_seq to authenticated;
