create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  visitor_token text not null,
  visited_at timestamptz not null default now()
);

create table if not exists public.product_clicks (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  clicked_at timestamptz not null default now()
);

alter table public.page_views enable row level security;
alter table public.product_clicks enable row level security;

create index if not exists page_views_visited_at_idx on public.page_views (visited_at);
create index if not exists product_clicks_product_id_idx on public.product_clicks (product_id);
create index if not exists product_clicks_clicked_at_idx on public.product_clicks (clicked_at);

create or replace function public.record_page_view(visitor_token text)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if visitor_token is null or length(visitor_token) < 16 or length(visitor_token) > 100 then return; end if;
  insert into public.page_views (visitor_token) values (visitor_token);
end;
$$;

create or replace function public.record_product_click(p_product_id bigint)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if exists (select 1 from public.products where id = p_product_id and active = true) then
    insert into public.product_clicks (product_id) values (p_product_id);
  end if;
end;
$$;

create or replace function public.get_page_view_stats()
returns json language plpgsql security definer set search_path = public
as $$
declare stats json;
begin
  if not public.is_admin() then
    raise exception 'Nur Admins dürfen Besucherstatistiken sehen.' using errcode = '42501';
  end if;
  select json_build_object(
    'total', (select count(*) from public.page_views),
    'today', (select count(*) from public.page_views where visited_at >= current_date),
    'last30', (select count(*) from public.page_views where visited_at >= now() - interval '30 days'),
    'products', coalesce((select json_agg(row_to_json(product_stats) order by product_stats.clicks desc, product_stats.name)
      from (select p.id, p.name, count(pc.id)::integer as clicks
            from public.products p join public.product_clicks pc on pc.product_id = p.id
            group by p.id, p.name order by count(pc.id) desc limit 10) product_stats), '[]'::json)
  ) into stats;
  return stats;
end;
$$;

grant execute on function public.record_page_view(text) to anon, authenticated;
grant execute on function public.record_product_click(bigint) to anon, authenticated;
grant execute on function public.get_page_view_stats() to authenticated;
