create table if not exists public.search_queries (
  id bigint generated by default as identity primary key,
  search_term text not null,
  visitor_token text,
  searched_at timestamptz not null default now()
);

alter table public.search_queries enable row level security;

create index if not exists search_queries_searched_at_idx on public.search_queries (searched_at);
create index if not exists search_queries_term_idx on public.search_queries (search_term);

create or replace function public.record_search_query(p_query text, p_visitor_token text default null)
returns void language plpgsql security definer set search_path = public
as $$
declare normalized_query text;
begin
  normalized_query := regexp_replace(btrim(coalesce(p_query, '')), '\s+', ' ', 'g');
  if length(normalized_query) < 2 or length(normalized_query) > 120 then return; end if;
  if p_visitor_token is not null and (length(p_visitor_token) < 16 or length(p_visitor_token) > 100) then
    p_visitor_token := null;
  end if;
  insert into public.search_queries (search_term, visitor_token) values (normalized_query, p_visitor_token);
end;
$$;

grant execute on function public.record_search_query(text, text) to anon, authenticated;

create or replace function public.get_page_view_stats()
returns json language plpgsql security definer set search_path = public
as $$
declare stats json;
begin
  if not public.is_admin() then
    raise exception 'Nur Admins dürfen Besucherstatistiken sehen.' using errcode = '42501';
  end if;
  select json_build_object(
    'total', (select count(*) from public.page_views),
    'today', (select count(*) from public.page_views where visited_at >= current_date),
    'last30', (select count(*) from public.page_views where visited_at >= now() - interval '30 days'),
    'products', coalesce((select json_agg(row_to_json(product_stats) order by product_stats.clicks desc, product_stats.name)
      from (select p.id, p.name, count(pc.id)::integer as clicks
            from public.products p join public.product_clicks pc on pc.product_id = p.id
            group by p.id, p.name order by count(pc.id) desc limit 10) product_stats), '[]'::json),
    'likes', coalesce((select json_agg(row_to_json(like_stats) order by like_stats.likes desc, like_stats.name)
      from (select p.id, p.name, count(pl.id)::integer as likes
            from public.products p join public.product_likes pl on pl.product_id = p.id
            group by p.id, p.name order by count(pl.id) desc limit 10) like_stats), '[]'::json),
    'recent_visits', coalesce((select json_agg(row_to_json(recent_visit) order by recent_visit.visited_at desc)
      from (select visited_at from public.page_views order by visited_at desc limit 50) recent_visit), '[]'::json),
    'searches', coalesce((select json_agg(row_to_json(search_stats) order by search_stats.searches desc, search_stats.search_term)
      from (select search_term, count(*)::integer as searches
            from public.search_queries where searched_at >= now() - interval '30 days'
            group by search_term order by count(*) desc, search_term limit 20) search_stats), '[]'::json),
    'recent_searches', coalesce((select json_agg(row_to_json(recent_search) order by recent_search.searched_at desc)
      from (select search_term, searched_at from public.search_queries order by searched_at desc limit 50) recent_search), '[]'::json)
  ) into stats;
  return stats;
end;
$$;

grant execute on function public.get_page_view_stats() to authenticated;

create or replace function public.reset_page_view_stats()
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Nur Admins dürfen Statistiken zurücksetzen.' using errcode = '42501';
  end if;
  delete from public.product_likes where true;
  delete from public.product_clicks where true;
  delete from public.page_views where true;
  delete from public.search_queries where true;
end;
$$;

grant execute on function public.reset_page_view_stats() to authenticated;
