alter table public.paypal_transactions alter column own_product_id drop not null;

create table if not exists public.paypal_transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.paypal_transactions(id) on delete cascade,
  own_product_id bigint not null references public.own_products(id) on delete restrict,
  price numeric(10,2) not null,
  unique (transaction_id, own_product_id)
);

create table if not exists public.download_events (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.paypal_transactions(id) on delete cascade,
  own_product_id bigint not null references public.own_products(id) on delete restrict,
  downloaded_at timestamptz not null default now()
);

alter table public.paypal_transaction_items enable row level security;
alter table public.download_events enable row level security;
create policy "Admins can read transaction items" on public.paypal_transaction_items for select to authenticated using ((select public.is_admin()));
create policy "Admins can read download events" on public.download_events for select to authenticated using ((select public.is_admin()));
grant select on public.paypal_transaction_items, public.download_events to authenticated;

