create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

-- The first existing account is the project owner/admin. Additional users
-- remain ordinary customers until explicitly added to admin_users.
insert into public.admin_users (user_id)
select id from auth.users order by created_at limit 1
on conflict (user_id) do nothing;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;

drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
  on public.categories for select
  using (active = true);

drop policy if exists "Admins can manage categories" on public.categories;
create policy "Admins can manage categories"
  on public.categories for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
  on public.products for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant insert, update, delete on public.products to authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;

insert into public.categories (name, sort_order)
select name, row_number() over () - 1
from (values
  ('Wohnzimmer'), ('Schlafzimmer'), ('Esszimmer'), ('Küche'), ('Küche & Küchenhelfer'),
  ('Küchenzubehör'), ('Kochen & Backen'), ('Geschirr & Besteck'), ('Gläser & Tassen'),
  ('Vorratsbehälter & Aufbewahrung'), ('Badezimmer'), ('Badzubehör'), ('Möbel'),
  ('Sofas & Sessel'), ('Tische'), ('Stühle'), ('Betten'), ('Matratzen'), ('Schränke'),
  ('Kommoden'), ('Regale'), ('Aufbewahrung & Organisation'), ('Körbe & Boxen'),
  ('Garderobe'), ('Beleuchtung'), ('Lampen'), ('Dekoration'), ('Bilder & Wanddekoration'),
  ('Spiegel'), ('Vasen & Pflanzen'), ('Kerzen & Düfte'), ('Textilien'), ('Teppiche'),
  ('Vorhänge & Rollos'), ('Kissen & Decken'), ('Bettwäsche'), ('Handtücher'), ('Haushalt'),
  ('Haushaltshelfer'), ('Reinigung'), ('Wäsche & Wäschepflege'), ('Mülltrennung & Abfalleimer'),
  ('Arbeitszimmer'), ('Schreibtische'), ('Büro & Organisation'), ('Kinderzimmer'), ('Baby & Kind'),
  ('Spielzeug'), ('Garten & Balkon'), ('Gartenmöbel'), ('Pflanzen & Pflanzgefäße'), ('Outdoor'),
  ('Eingangsbereich & Flur'), ('Smart Home'), ('Sicherheit'), ('Werkzeug & Heimwerken'), ('Reise'),
  ('Reisezubehör'), ('Taschen & Gepäck'), ('Haustiere'), ('Hunde'), ('Katzen'), ('Tierbedarf'),
  ('DVDs & Blu-rays'), ('CDs & Musik'), ('Filme & Serien'), ('Gaming'), ('Konsolen'),
  ('Konsolenzubehör'), ('Controller'), ('Gaming-Zubehör'), ('Gaming-Headsets'), ('PC & Computer'),
  ('Laptops & Notebooks'), ('PC-Zubehör'), ('Laptop-Zubehör'), ('Monitore'), ('Tastaturen'),
  ('Mäuse'), ('Webcams'), ('Headsets & Mikrofone'), ('Lautsprecher'), ('Festplatten & SSDs'),
  ('USB-Sticks & Speicher'), ('Kabel & Adapter'), ('Ladegeräte & Netzteile'), ('Drucker & Scanner'),
  ('Netzwerk & WLAN'), ('Router'), ('Gaming-PCs'), ('Gaming-Laptops'), ('Gaming-Monitore'),
  ('PC-Komponenten')
) as seed(name)
on conflict (name) do nothing;
