create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  email text,
  topic text not null,
  message text not null,
  is_read boolean not null default false,
  constraint contact_topic_length check (char_length(trim(topic)) between 1 and 140),
  constraint contact_message_length check (char_length(trim(message)) between 1 and 3000),
  constraint contact_name_length check (name is null or char_length(name) <= 100),
  constraint contact_email_length check (email is null or char_length(email) <= 200)
);

create index if not exists contact_messages_created_at_idx on public.contact_messages (created_at desc);
create index if not exists contact_messages_is_read_idx on public.contact_messages (is_read);

alter table public.contact_messages enable row level security;

create policy "Anyone can submit contact messages"
  on public.contact_messages for insert
  to anon, authenticated
  with check (
    char_length(trim(topic)) between 1 and 140
    and char_length(trim(message)) between 1 and 3000
    and (name is null or char_length(name) <= 100)
    and (email is null or char_length(email) <= 200)
  );

create policy "Admins can read contact messages"
  on public.contact_messages for select
  to authenticated
  using (public.is_admin());

create policy "Admins can update contact messages"
  on public.contact_messages for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admins can delete contact messages"
  on public.contact_messages for delete
  to authenticated
  using (public.is_admin());

grant insert on table public.contact_messages to anon, authenticated;
grant select, update, delete on table public.contact_messages to authenticated;
