-- Products made and sold directly by Findora Home.
-- Public visitors can only see active items; only the existing admin can manage them.
create table if not exists public.own_products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  description text not null default '',
  price numeric(10,2),
  image_url text,
  purchase_url text,
  active boolean not null default true,
  constraint own_product_name_length check (char_length(trim(name)) between 1 and 140),
  constraint own_product_description_length check (char_length(description) <= 3000),
  constraint own_product_price_nonnegative check (price is null or price >= 0),
  constraint own_product_purchase_url_length check (purchase_url is null or char_length(purchase_url) <= 1000)
);

alter table public.own_products enable row level security;

drop policy if exists "Public can read active own products" on public.own_products;
create policy "Public can read active own products"
  on public.own_products for select
  using (active = true);

drop policy if exists "Admins can manage own products" on public.own_products;
create policy "Admins can manage own products"
  on public.own_products for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

grant select on public.own_products to anon, authenticated;
grant insert, update, delete on public.own_products to authenticated;
grant usage, select on sequence public.own_products_id_seq to authenticated;
