alter table public.products add column if not exists partner text;

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.partners enable row level security;

drop policy if exists "Public can read active partners" on public.partners;
create policy "Public can read active partners"
  on public.partners for select
  using (active = true);

drop policy if exists "Admins can manage partners" on public.partners;
create policy "Admins can manage partners"
  on public.partners for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

grant select on public.partners to anon, authenticated;
grant insert, update, delete on public.partners to authenticated;
grant usage, select on sequence public.partners_id_seq to authenticated;

insert into public.partners (name, sort_order)
select name, row_number() over () - 1
from (values ('Amazon'), ('IKEA'), ('SHEIN'), ('Temu')) as seed(name)
on conflict (name) do nothing;
